In [65]:
import numpy as np
import pandas as pd

1. Importing DataSets

In [66]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [67]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [68]:
credits.head(2)['crew']

0    [{"credit_id": "52fe48009251416c750aca23", "de...
1    [{"credit_id": "52fe4232c3a36847f800b579", "de...
Name: crew, dtype: object

In [69]:
# merge the two dataframes

movies = movies.merge(credits, on = 'title')

In [70]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."


2. Data Preprocessing

In [71]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [72]:
# genres
# id -> to fetch the movie posters
# keywords
# title
# overview
# cast
# crew

movies = movies[['genres', 'id', 'title', 'keywords','overview', 'cast', 'crew']]

In [73]:
movies.isnull().sum()

genres      0
id          0
title       0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [74]:
movies.dropna(inplace = True)

In [75]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [76]:
# ast converts gneres (list with string indices) to list with int indices
import ast

def convert_to_tags(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [77]:
movies['genres'] = movies['genres'].apply(convert_to_tags)

In [78]:
movies['keywords'] = movies['keywords'].apply(convert_to_tags)

In [79]:
movies.head()

,genres,id,title,keywords,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,Avatar,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,John Carter,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [80]:
def cast_to_tags(obj):
    L = []
    cnt = 0
    for i in ast.literal_eval(obj):
        if cnt < 3:
            L.append(i['name'])
            cnt += 1
        else:
            break
        
    return L

In [81]:
movies['cast'] = movies['cast'].apply(cast_to_tags)

In [82]:
movies.iloc[0].crew

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [83]:
def crew_to_tags(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [84]:
movies['crew'] = movies['crew'].apply(crew_to_tags)

In [85]:
movies.head()

,genres,id,title,keywords,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,Avatar,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,John Carter,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [86]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [87]:
# converting overview from str to a list

movies['overview'] = movies['overview'].apply(lambda x : x.split())

In [88]:
movies['overview']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [89]:
movies.head()

,genres,id,title,keywords,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,Avatar,"[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,John Carter,"[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [90]:
# now, for the model to work better
# we need to remove the spaces in between the words

movies['genres'].apply(lambda x : [i.replace(" ", "") for i in x])

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [91]:
movies['genres'] = movies['genres'].apply(lambda x : [i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x : [i.replace(" ", "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x : [i.replace(" ", "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x : [i.replace(" ", "") for i in x])

In [92]:
movies.head(2)

,genres,id,title,keywords,overview,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,"[Adventure, Fantasy, Action]",285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]

In [93]:
# append all of other cols to tags

movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [94]:
movies.head(2)

,genres,id,title,keywords,overview,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."

In [95]:
# making a new df only by taking the required columns

new_df = movies[['id', 'title', 'tags']]

In [96]:
new_df.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [97]:
# convert tags to a string

new_df['tags'] = [" ".join(x) for x in new_df['tags']]

C:\Users\Akhil Elumagandla\AppData\Local\Temp\ipykernel_13584\386883324.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = [" ".join(x) for x in new_df['tags']]

In [98]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4806 entries, 0 to 4808
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4806 non-null   int64
 1   title   4806 non-null   object
 2   tags    4806 non-null   object
dtypes: int64(1), object(2)
memory usage: 279.2+ KB

In [99]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [100]:
# convert all the letters to lower case

new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\Akhil Elumagandla\AppData\Local\Temp\ipykernel_13584\794348567.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [101]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [102]:
import nltk

In [103]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [104]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [105]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Akhil Elumagandla\AppData\Local\Temp\ipykernel_13584\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

2. Vectorization

In [106]:
# Bag of words technique

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [107]:
# convert it to a numpy array

vectors = cv.fit_transform(new_df['tags']).toarray()

In [108]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [109]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [110]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

3. Cosine Similarity

In [111]:
from sklearn.metrics.pairwise import cosine_similarity

In [112]:
similarity = cosine_similarity(vectors)

In [113]:
similarity

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]], shape=(4806, 4806))

In [114]:
sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x : x[1])

[(0, np.float64(0.9999999999999998)),
 (1214, np.float64(0.2867696673382022)),
 (2405, np.float64(0.26901379342448517)),
 (3728, np.float64(0.2605130246476754)),
 (507, np.float64(0.255608593705383)),
 (539, np.float64(0.25038669783359574)),
 (582, np.float64(0.24511108480187255)),
 (1202, np.float64(0.24455799402225922)),
 (1192, np.float64(0.2367785320221084)),
 (61, np.float64(0.23179316248638276)),
 (778, np.float64(0.23174488732966075)),
 (4046, np.float64(0.2278389747471728)),
 (1916, np.float64(0.2252817784447915)),
 (2782, np.float64(0.21853668936906193)),
 (172, np.float64(0.21239769762143662)),
 (972, np.float64(0.2108663315950723)),
 (322, np.float64(0.2105263157894737)),
 (2329, np.float64(0.20443988269091462)),
 (3606, np.float64(0.20437977982832192)),
 (260, np.float64(0.20395079136182276)),
 (151, np.float64(0.2029530274475215)),
 (4190, np.float64(0.2029530274475215)),
 (1440, np.float64(0.20277677641345318)),
 (74, np.float64(0.20246457179963145)),
 (1087, np.float64(0.2020475485519274)),
 (3671, np.float64(0.1979082783981174)),
 (973, np.float64(0.19767387315371682)),
 (577, np.float64(0.1976738731537168)),
 (47, np.float64(0.19672236884115843)),
 (2969, np.float64(0.19252140716412977)),
 (942, np.float64(0.19134594929397597)),
 (495, np.float64(0.19088542889273336)),
 (1199, np.float64(0.19088542889273336)),
 (305, np.float64(0.19007487139298027)),
 (4, np.float64(0.1892994097121204)),
 (4405, np.float64(0.18731716231633883)),
 (94, np.float64(0.1873171623163388)),
 (27, np.float64(0.18693292157876878)),
 (3325, np.float64(0.1860807318911967)),
 (1273, np.float64(0.18394180184548975)),
 (1327, np.float64(0.18394180184548975)),
 (2997, np.float64(0.1813690625275029)),
 (3997, np.float64(0.18074256993863339)),
 (83, np.float64(0.17996850826633906)),
 (1069, np.float64(0.17954621161490197)),
 (220, np.float64(0.1777046633277277)),
 (184, np.float64(0.177343107178349)),
 (1319, np.float64(0.17699808135119718)),
 (168, np.float64(0.17521916101261562)),
 (2200, np.float64(0.17521916101261562)),
 (4336, np.float64(0.17521916101261562)),
 (931, np.float64(0.1748149640244195)),
 (36, np.float64(0.17316974359835272)),
 (373, np.float64(0.17292861596651865)),
 (300, np.float64(0.17119059581558146)),
 (3536, np.float64(0.17119059581558146)),
 (3160, np.float64(0.170405729136922)),
 (1978, np.float64(0.16943474841747153)),
 (661, np.float64(0.16754156331667822)),
 (529, np.float64(0.16742770563222897)),
 (1827, np.float64(0.16742770563222897)),
 (91, np.float64(0.16692446522239718)),
 (41, np.float64(0.16563698349810535)),
 (67, np.float64(0.16452254913212452)),
 (150, np.float64(0.16426202236672155)),
 (1533, np.float64(0.16222142113076252)),
 (342, np.float64(0.16122923187750418)),
 (595, np.float64(0.16059101370939324)),
 (31, np.float64(0.15907119074394446)),
 (2511, np.float64(0.15907119074394446)),
 (1176, np.float64(0.15789473684210528)),
 (4008, np.float64(0.15737789507292674)),
 (2727, np.float64(0.15609763526361567)),
 (149, np.float64(0.15511334686589626)),
 (838, np.float64(0.1540171257313038)),
 (26, np.float64(0.15389675281277312)),
 (187, np.float64(0.15389675281277312)),
 (1379, np.float64(0.152008377581442)),
 (111, np.float64(0.15018785229652767)),
 (1342, np.float64(0.15018785229652767)),
 (311, np.float64(0.15018785229652765)),
 (52, np.float64(0.14843120879858804)),
 (513, np.float64(0.14843120879858804)),
 (2071, np.float64(0.14808721943977307)),
 (7, np.float64(0.14673479641335554)),
 (2756, np.float64(0.14659886790209342)),
 (127, np.float64(0.14601068654819696)),
 (579, np.float64(0.14567913668701626)),
 (581, np.float64(0.14567913668701626)),
 (108, np.float64(0.14509525002200235)),
 (1295, np.float64(0.14509525002200235)),
 (466, np.float64(0.14509525002200233)),
 (1392, np.float64(0.14421498760030763)),
 (1475, np.float64(0.1442149876003076)),
 (1353, np.float64(0.14350946197048198)),
 (1934, np.float64(0.14350946197048198)),
 (275, np.float64(0.1433848336691011)),
 (294, np.float64(0.1433848336691011)),
 (3352, np.float64(0.1433848336691011)),
 (1054, np.float64(0.1419745572840903)),
 (1271, np.float64(0.1419745572840903)),
 (490, np.float64(0.14159846508095775)),
 (1484, np.float64(0.14159846508095775)),
 (413, np.float64(0.1411956236812263)),
 (2492, np.float64(0.1411956236812263)),
 (461, np.float64(0.14119562368122626)),
 (568, np.float64(0.14119562368122626)),
 (95, np.float64(0.1404878717372541)),
 (17, np.float64(0.13977653617040256)),
 (46, np.float64(0.1391037210186643)),
 (3407, np.float64(0.1391037210186643)),
 (1961, np.float64(0.13872950617564817)),
 (56, np.float64(0.13834289277321493)),
 (249, np.float64(0.13834289277321493)),
 (1325, np.float64(0.13834289277321493)),
 (3779, np.float64(0.13834289277321493)),
 (72, np.float64(0.13710212427677043)),
 (843, np.float64(0.13710212427677043)),
 (859, np.float64(0.13710212427677043)),
 (2165, np.float64(0.13710212427677043)),
 (4538, np.float64(0.13629325512727639)),
 (476, np.float64(0.13530201829834768)),
 (505, np.float64(0.13530201829834768)),
 (668, np.float64(0.13530201829834768)),
 (935, np.float64(0.13530201829834768)),
 (3980, np.float64(0.13530201829834768)),
 (1804, np.float64(0.1351845176089688)),
 (4348, np.float64(0.13497638119975428)),
 (1320, np.float64(0.13476498501489081)),
 (158, np.float64(0.13369695534647594)),
 (502, np.float64(0.13369695534647594)),
 (777, np.float64(0.13369695534647594)),
 (126, np.float64(0.13334518676566626)),
 (1556, np.float64(0.13334518676566626)),
 (1369, np.float64(0.1324532357065044)),
 (2374, np.float64(0.1324532357065044)),
 (2580, np.float64(0.1324532357065044)),
 (4077, np.float64(0.13157894736842107)),
 (2129, np.float64(0.13124359177794215)),
 (1013, np.float64(0.12988108336653278)),
 (2177, np.float64(0.12988108336653278)),
 (3620, np.float64(0.12988108336653278)),
 (134, np.float64(0.12977713690461004)),
 (368, np.float64(0.12977713690461004)),
 (1770, np.float64(0.12977713690461004)),
 (2869, np.float64(0.12892051277806202)),
 (14, np.float64(0.12824729401064427)),
 (138, np.float64(0.12824729401064427)),
 (369, np.float64(0.12824729401064427)),
 (1084, np.float64(0.12824729401064427)),
 (2682, np.float64(0.12824729401064427)),
 (4228, np.float64(0.12824729401064427)),
 (487, np.float64(0.12725695259515557)),
 (773, np.float64(0.12725695259515557)),
 (2968, np.float64(0.12725695259515557)),
 (937, np.float64(0.126673647984535)),
 (1737, np.float64(0.12565617248750865)),
 (2476, np.float64(0.12565617248750865)),
 (166, np.float64(0.12515654358043973)),
 (754, np.float64(0.12515654358043973)),
 (2446, np.float64(0.12515654358043973)),
 (3626, np.float64(0.12515654358043973)),
 (483, np.float64(0.12487810821089253)),
 (1094, np.float64(0.12487810821089253)),
 (1156, np.float64(0.12487810821089253)),
 (2648, np.float64(0.12487810821089253)),
 (102, np.float64(0.12462194771917919)),
 (84, np.float64(0.12361284651454937)),
 (208, np.float64(0.12262786789699316)),
 (3374, np.float64(0.12262786789699316)),
 (1874, np.float64(0.12262786789699313)),
 (438, np.float64(0.12227899701112963)),
 (557, np.float64(0.12227899701112963)),
 (1297, np.float64(0.12227899701112961)),
 (2327, np.float64(0.12166606584807191)),
 (2670, np.float64(0.12166606584807191)),
 (3081, np.float64(0.12166606584807191)),
 (139, np.float64(0.12072654548783007)),
 (68, np.float64(0.1204950466257556)),
 (781, np.float64(0.1204950466257556)),
 (1002, np.float64(0.1204950466257556)),
 (1272, np.float64(0.1204950466257556)),
 (1654, np.float64(0.1204950466257556)),
 (1000, np.float64(0.11980845957463077)),
 (549, np.float64(0.11959121830873498)),
 (870, np.float64(0.11959121830873498)),
 (900, np.float64(0.11959121830873498)),
 (3233, np.float64(0.11959121830873498)),
 (1045, np.float64(0.11846977555181847)),
 (1829, np.float64(0.11846977555181847)),
 (2056, np.float64(0.11846977555181847)),
 (2737, np.float64(0.11846977555181847)),
 (4673, np.float64(0.11846977555181847)),
 (1669, np.float64(0.11803342130469506)),
 (1711, np.float64(0.11803342130469506)),
 (2785, np.float64(0.11803342130469506)),
 (3719, np.float64(0.11803342130469506)),
 (3998, np.float64(0.11803342130469506)),
 (160, np.float64(0.11712303424679457)),
 (454, np.float64(0.11707322644771176)),
 (182, np.float64(0.11707322644771175)),
 (278, np.float64(0.11707322644771175)),
 (1613, np.float64(0.11707322644771175)),
 (2280, np.float64(0.11707322644771175)),
 (28, np.float64(0.116543309349613)),
 (122, np.float64(0.116543309349613)),
 (422, np.float64(0.116543309349613)),
 (678, np.float64(0.116543309349613)),
 (589, np.float64(0.1163350101494222)),
 (2543, np.float64(0.11587244366483038)),
 (1493, np.float64(0.11551284429847784)),
 (3210, np.float64(0.11506355109724453)),
 (189, np.float64(0.1147078669352809)),
 (236, np.float64(0.11470786693528089)),
 (1299, np.float64(0.11470786693528089)),
 (1218, np.float64(0.11470786693528087)),
 (85, np.float64(0.1141270638770543)),
 (432, np.float64(0.11357771260606365)),
 (1414, np.float64(0.11357771260606365)),
 (50, np.float64(0.11295649894498101)),
 (1612, np.float64(0.11295649894498101)),
 (123, np.float64(0.1124803176664619)),
 (420, np.float64(0.1124803176664619)),
 (536, np.float64(0.1124803176664619)),
 (889, np.float64(0.11243619908556624)),
 (3145, np.float64(0.11239029738980326)),
 (256, np.float64(0.11164843913471803)),
 (808, np.float64(0.11164843913471803)),
 (1346, np.float64(0.11164843913471803)),
 (1571, np.float64(0.11164843913471803)),
 (2368, np.float64(0.11141412945539662)),
 (3307, np.float64(0.11141412945539662)),
 (1508, np.float64(0.11141412945539661)),
 (87, np.float64(0.11128297681493143)),
 (121, np.float64(0.11128297681493143)),
 (232, np.float64(0.11128297681493143)),
 (4468, np.float64(0.11128297681493143)),
 (206, np.float64(0.11092107999698035)),
 (238, np.float64(0.11092107999698035)),
 (228, np.float64(0.11037769642208699)),
 (81, np.float64(0.11020775375559676)),
 (1570, np.float64(0.11020775375559676)),
 (3426, np.float64(0.10968169942141637)),
 (21, np.float64(0.10968169942141635)),
 (449, np.float64(0.10968169942141635)),
 (1029, np.float64(0.10968169942141635)),
 (1941, np.float64(0.10968169942141635)),
 (2144, np.float64(0.10968169942141635)),
 (3006, np.float64(0.10968169942141635)),
 (692, np.float64(0.10936965981495178)),
 (200, np.float64(0.10882143751650175)),
 (627, np.float64(0.10882143751650175)),
 (653, np.float64(0.10882143751650175)),
 (1520, np.float64(0.10882143751650175)),
 (307, np.float64(0.10876595882948199)),
 (5, np.float64(0.10838874619051501)),
 (740, np.float64(0.10838874619051501)),
 (3091, np.float64(0.10838874619051501)),
 (3628, np.float64(0.10838874619051501)),
 (786, np.float64(0.10814761408717503)),
 (3496, np.float64(0.10814761408717503)),
 (4777, np.float64(0.10814761408717502)),
 (229, np.float64(0.1074861545850028)),
 (572, np.float64(0.10743376064838502)),
 (939, np.float64(0.1068366854693644)),
 (332, np.float64(0.106676149412533)),
 (472, np.float64(0.106676149412533)),
 (1235, np.float64(0.106676149412533)),
 (170, np.float64(0.10650358071057624)),
 (262, np.float64(0.10650358071057624)),
 (1164, np.float64(0.10619884881071831)),
 (1497, np.float64(0.10619884881071831)),
 (1741, np.float64(0.10619884881071831)),
 (2157, np.float64(0.10619884881071831)),
 (2630, np.float64(0.10619884881071831)),
 (4133, np.float64(0.10619884881071831)),
 (467, np.float64(0.10559715077387793)),
 (541, np.float64(0.10559715077387793)),
 (1492, np.float64(0.10559715077387793)),
 (131, np.float64(0.10526315789473685)),
 (295, np.float64(0.10526315789473685)),
 (2068, np.float64(0.10526315789473685)),
 (3338, np.float64(0.10526315789473685)),
 (2494, np.float64(0.10471347707292389)),
 (75, np.float64(0.10390486669322622)),
 (223, np.float64(0.10390486669322622)),
 (687, np.float64(0.10390486669322622)),
 (814, np.float64(0.10390486669322622)),
 (1193, np.float64(0.10390486669322622)),
 (1767, np.float64(0.10390486669322622)),
 (2813, np.float64(0.10390486669322622)),
 (654, np.float64(0.10385162309931599)),
 (2435, np.float64(0.10385162309931599)),
 (105, np.float64(0.1037571695799112)),
 (233, np.float64(0.1037571695799112)),
 (624, np.float64(0.1037571695799112)),
 (2319, np.float64(0.1037571695799112)),
 (2452, np.float64(0.1037571695799112)),
 (2517, np.float64(0.1037571695799112)),
 (3053, np.float64(0.1037571695799112)),
 (3619, np.float64(0.1037571695799112)),
 (3837, np.float64(0.1037571695799112)),
 (1451, np.float64(0.10301070542879115)),
 (10, np.float64(0.10259783520851541)),
 (1080, np.float64(0.10259783520851541)),
 (3150, np.float64(0.10259783520851541)),
 (3632, np.float64(0.10259783520851541)),
 (3753, np.float64(0.10259783520851541)),
 (3872, np.float64(0.10259783520851541)),
 (4095, np.float64(0.10259783520851541)),
 (2102, np.float64(0.10218988991416095)),
 (2758, np.float64(0.10147651372376076)),
 (3659, np.float64(0.10147651372376076)),
 (3952, np.float64(0.10147651372376076)),
 (3439, np.float64(0.10138838820672659)),
 (508, np.float64(0.101338918387628)),
 (1292, np.float64(0.101338918387628)),
 (2243, np.float64(0.10133891838762799)),
 (1401, np.float64(0.10060545457319173)),
 (1435, np.float64(0.10060545457319173)),
 (2095, np.float64(0.10060545457319173)),
 (312, np.float64(0.10012523486435178)),
 (330, np.float64(0.10012523486435178)),
 (643, np.float64(0.10012523486435178)),
 (986, np.float64(0.10012523486435178)),
 (1035, np.float64(0.10012523486435178)),
 (1610, np.float64(0.10012523486435178)),
 (35, np.float64(0.09933992677987831)),
 (157, np.float64(0.09933992677987831)),
 (319, np.float64(0.09933992677987831)),
 (325, np.float64(0.09933992677987831)),
 (715, np.float64(0.09933992677987831)),
 (1075, np.float64(0.09933992677987831)),
 (1278, np.float64(0.09933992677987831)),
 (1880, np.float64(0.09933992677987831)),
 (2049, np.float64(0.09933992677987831)),
 (4016, np.float64(0.09933992677987831)),
 (4196, np.float64(0.09933992677987831)),
 (4490, np.float64(0.09933992677987831)),
 (363, np.float64(0.09909250441117726)),
 (491, np.float64(0.09909250441117726)),
 (266, np.float64(0.0989541391990587)),
 (445, np.float64(0.0989541391990587)),
 (510, np.float64(0.0989541391990587)),
 (3618, np.float64(0.0989541391990587)),
 (3781, np.float64(0.0989541391990587)),
 (3933, np.float64(0.0989541391990587)),
 (1771, np.float64(0.09836118442057921)),
 (410, np.float64(0.09782319760890369)),
 (480, np.float64(0.09782319760890369)),
 (535, np.float64(0.09782319760890369)),
 (898, np.float64(0.09782319760890369)),
 (1107, np.float64(0.09782319760890369)),
 (1397, np.float64(0.09782319760890369)),
 (1819, np.float64(0.09782319760890369)),
 (2249, np.float64(0.09782319760890369)),
 (33, np.float64(0.09733285267845754)),
 (148, np.float64(0.09733285267845754)),
 (263, np.float64(0.09733285267845754)),
 (878, np.float64(0.09733285267845754)),
 (1154, np.float64(0.09733285267845754)),
 (1723, np.float64(0.09733285267845754)),
 (1938, np.float64(0.09733285267845754)),
 (2783, np.float64(0.09733285267845754)),
 (4254, np.float64(0.09733285267845754)),
 (4403, np.float64(0.09733285267845754)),
 (4472, np.float64(0.09733285267845754)),
 (9, np.float64(0.0967301666813349)),
 (334, np.float64(0.0967301666813349)),
 (371, np.float64(0.09567297464698798)),
 (412, np.float64(0.09567297464698798)),
 (2237, np.float64(0.09567297464698798)),
 (2552, np.float64(0.09567297464698798)),
 (4545, np.float64(0.09558988911273408)),
 (362, np.float64(0.09544271444636668)),
 (791, np.float64(0.09544271444636668)),
 (1569, np.float64(0.09544271444636668)),
 (2558, np.float64(0.09544271444636668)),
 (4201, np.float64(0.09544271444636668)),
 (18, np.float64(0.09493290614465533)),
 (11, np.float64(0.09464970485606021)),
 (587, np.float64(0.09464970485606021)),
 (1274, np.float64(0.09365858115816941)),
 (1355, np.float64(0.09365858115816941)),
 (3718, np.float64(0.09365858115816941)),
 (4502, np.float64(0.09365858115816941)),
 (660, np.float64(0.0936585811581694)),
 (920, np.float64(0.0936585811581694)),
 (978, np.float64(0.0936585811581694)),
 (1470, np.float64(0.0936585811581694)),
 (1682, np.float64(0.0936585811581694)),
 (1688, np.float64(0.0936585811581694)),
 (1717, np.float64(0.0936585811581694)),
 (2392, np.float64(0.0936585811581694)),
 (2484, np.float64(0.0936585811581694)),
 (2588, np.float64(0.0936585811581694)),
 (2641, np.float64(0.0936585811581694)),
 (2646, np.float64(0.0936585811581694)),
 (2816, np.float64(0.0936585811581694)),
 (3535, np.float64(0.0936585811581694)),
 (4331, np.float64(0.0936585811581694)),
 (301, np.float64(0.09365858115816939)),
 (596, np.float64(0.09269795493186431)),
 (129, np.float64(0.0926979549318643)),
 (243, np.float64(0.0926979549318643)),
 (279, np.float64(0.0926979549318643)),
 (473, np.float64(0.0926979549318643)),
 (813, np.float64(0.0926979549318643)),
 (1442, np.float64(0.0926979549318643)),
 (1697, np.float64(0.0926979549318643)),
 (3405, np.float64(0.0926979549318643)),
 (785, np.float64(0.09243423333081695)),
 (219, np.float64(0.09197090092274487)),
 (244, np.float64(0.09197090092274487)),
 (511, np.float64(0.09197090092274487)),
 (1752, np.float64(0.09197090092274487)),
 (2089, np.float64(0.09197090092274487)),
 (2647, np.float64(0.09197090092274487)),
 (3734, np.float64(0.09197090092274487)),
 (230, np.float64(0.09183979479633063)),
 (799, np.float64(0.09183979479633063)),
 (239, np.float64(0.09125667909262308)),
 (2566, np.float64(0.09125667909262308)),
 (43, np.float64(0.09086217008485092)),
 (602, np.float64(0.09086217008485092)),
 (995, np.float64(0.09086217008485092)),
 (1231, np.float64(0.09086217008485092)),
 (1842, np.float64(0.09086217008485092)),
 (3879, np.float64(0.09086217008485092)),
 (12, np.float64(0.09037128496931669)),
 (88, np.float64(0.09037128496931669)),
 (167, np.float64(0.09037128496931669)),
 (356, np.float64(0.09037128496931669)),
 (400, np.float64(0.09037128496931669)),
 (1304, np.float64(0.09037128496931669)),
 (1476, np.float64(0.09037128496931669)),
 (2247, np.float64(0.09037128496931669)),
 (2955, np.float64(0.09037128496931669)),
 (331, np.float64(0.08998425413316952)),
 (2359, np.float64(0.08998425413316952)),
 (2792, np.float64(0.08998425413316952)),
 (2852, np.float64(0.08998425413316952)),
 (3387, np.float64(0.08998425413316952)),
 (3441, np.float64(0.08998425413316952)),
 (3460, np.float64(0.08998425413316952)),
 (4343, np.float64(0.08998425413316952)),
 (4353, np.float64(0.08998425413316952)),
 (274, np.float64(0.08977310580745099)),
 (1902, np.float64(0.0891313035643173)),
 (2111, np.float64(0.08903057122447033)),
 (292, np.float64(0.08885233166386385)),
 (564, np.float64(0.08885233166386385)),
 (1025, np.float64(0.08885233166386385)),
 (2656, np.float64(0.08885233166386385)),
 (2864, np.float64(0.08885233166386385)),
 (3320, np.float64(0.08885233166386385)),
 (169, np.float64(0.08830215713766959)),
 (270, np.float64(0.08830215713766959)),
 (618, np.float64(0.08830215713766959)),
 (1779, np.float64(0.08830215713766959)),
 (2105, np.float64(0.08830215713766959)),
 (2709, np.float64(0.08830215713766959)),
 (2736, np.float64(0.08830215713766959)),
 (3551, np.float64(0.08830215713766959)),
 (479, np.float64(0.08797691788472335)),
 (752, np.float64(0.08749572785196143)),
 (1828, np.float64(0.08749572785196143)),
 (2444, np.float64(0.08746392856766495)),
 (23, np.float64(0.08740748201220976)),
 (141, np.float64(0.08740748201220976)),
 (389, np.float64(0.08740748201220976)),
 (745, np.float64(0.08740748201220976)),
 (794, np.float64(0.08740748201220976)),
 (960, np.float64(0.08740748201220976)),
 (1247, np.float64(0.08740748201220976)),
 (1257, np.float64(0.08740748201220976)),
 (3446, np.float64(0.08740748201220976)),
 (3447, np.float64(0.08740748201220976)),
 (143, np.float64(0.08671099695241201)),
 (199, np.float64(0.08671099695241201)),
 (827, np.float64(0.08671099695241201)),
 (1526, np.float64(0.08671099695241201)),
 (2876, np.float64(0.08671099695241201)),
 (3554, np.float64(0.08671099695241201)),
 (4516, np.float64(0.08671099695241201)),

In [119]:
def recommend(movie):
    movie_ind = new_df[new_df['title'] == movie].index[0]
    dist = similarity[movie_ind]
    L = sorted(list(enumerate(dist)), reverse = True, key = lambda x : x[1])[1 : 6]

    for i in L:
        print(new_df.iloc[i[0]].title)

In [122]:
recommend('Inception')

12 Rounds
RED
Abduction
Krrish
The Animal

In [123]:
import pickle

In [124]:
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [125]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))